language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo apt-get install e2fslibs-dev

script:
  - cmake --version
  - mkdir build && cd build
  - cmake ..
  - make

after_success:
  # create empty 128M file
  - dd if=/dev/zero of=fs_file count=128 bs=1M
  # create file system on the file
  - mkfs.ext2 -b 1024 -F fs_file
  - sudo losetup /dev/loop20 fs_file
  - sudo ./dump_layout /dev/loop20
  - sudo ./dump_del /dev/loop20

notifications:
  email: false